In [46]:
import numpy as np

### ⚡ Why is NumPy Faster Than Lists?

NumPy arrays are stored at **one continuous block of memory**, unlike Python lists which store elements at **scattered memory locations**.

This enables:

- **Efficient memory access**
- **Faster processing and computation**

This behavior is known as **locality of reference** in computer science.

---

### 🧠 Key Reasons for NumPy's Speed:

- 🧱 **Contiguous memory layout** (vs. scattered memory in lists)
- 🚀 **Optimized C and Fortran backend**
- 🔄 **Vectorized operations** (no need for Python loops)
- 🧠 **Better use of CPU cache and registers**
- ⚙️ **Takes advantage of modern CPU architectures**

---

✅ **Conclusion**:  
NumPy is faster than lists primarily because of its **low-level memory efficiency** and **hardware-level optimizations**.


---

## 1> Check Number of Dimensions?

NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [47]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


When the array is created, you can define the number of dimensions by using the **ndmin** argument.

In [48]:
# Create an array with 5 dimensions and verify that it has 5 dimensions:

arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
print('number of dimensions :', arr.ndim)
arr[0,0,0,0,0]

[[[[[1 2 3 4]]]]]
number of dimensions : 5


np.int64(1)

---

## 2> NumPy Array Indexing

In [49]:
# Get third and fourth elements from the following array and add them.
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [50]:
# Access the element on the first row, second column:
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [51]:
# Access the element on the 2nd row, 5th column:
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [52]:
# Access the third element of the second array of the first array:
arr = np.array([[[1, 2, 3], [4, 5, 6]],
                [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [53]:
# Print the last element from the 2nd dim:
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


---

## 3> 🔪 Slicing in NumPy

In NumPy, we can extract parts of an array using slicing. Instead of passing a single index, we use the syntax:

[start:end]

We can also define a step value using:

[start:end:step]

---

### 🧠 Slicing Rules:

- **start** → starting index (default is 0 if omitted)
- **end** → ending index (exclusive; defaults to the length of the array if omitted)
- **step** → step size (default is 1 if omitted)

Slicing allows efficient access and manipulation of subsets of data in arrays.


In [54]:
# Slice elements from index 1 to index 5 from the following array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [55]:
# Slice elements from index 4 to the end of the array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [56]:
# Slice elements from the beginning to index 4 (not included):
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [57]:
# Slice from the index 3 from the end to index 1 from the end:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [58]:
# Return every other element from index 1 to index 5:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])

[2 4]


In [59]:
# Return every other element from the entire array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [60]:
# From the second element, slice elements from index 1 to index 4 (not included):
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])
print(arr[1, 1:4])

[7 8 9]


In [61]:
# From both elements, return index 2:
arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])
print(arr[0:2,2])

[3 8]


In [62]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

arr = np.array([[1, 2, 3, 4, 5],
                [6, 7, 8, 9, 10]])
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


---

## 4> NumPy Data Types

📊 Data Types in NumPy
NumPy has additional data types that are represented using single-character codes. Here's a list of the common data types and their corresponding characters:
| Code | Data Type                                 |
| ---- | ----------------------------------------- |
| `i`  | Integer                                   |
| `b`  | Boolean                                   |
| `u`  | Unsigned Integer                          |
| `f`  | Float                                     |
| `c`  | Complex Float                             |
| `m`  | Timedelta                                 |
| `M`  | Datetime                                  |
| `O`  | Object                                    |
| `S`  | String (byte string)                      |
| `U`  | Unicode String                            |
| `V`  | Raw data (Void / Fixed-size memory block) |

In [63]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)

int64


In [64]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [65]:
# Create an array with data type string:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


For i, u, f, S and U we can define size as well.

In [66]:
# Create an array with data type 4 bytes integer:
arr = np.array([1, 2, 3, 4], dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [67]:
# A non integer string like 'a' can not be converted to integer (will raise an error):

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

🔄 Converting Data Type on Existing Arrays in NumPy
The best way to change the data type of an existing NumPy array is by creating a copy using the .astype() method.

🧠 What .astype() Does:
Creates a new array (original remains unchanged)

Allows you to specify the target data type

Accepts: 
String representations (e.g., 'f' for float, 'i' for integer)

Python data types (e.g., float, int)

In [ ]:
# Change data type from float to integer by using 'i' as parameter value:

arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [ ]:
# Change data type from float to integer by using int as parameter value:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [ ]:
# Change data type from integer to boolean:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


---

## 5> NumPy Array Copy vs View

## 🆚 The Difference Between Copy and View in NumPy

In NumPy, understanding the difference between a **copy** and a **view** is essential when working with arrays.

---

### 🧾 **Copy**
- A **copy** creates a **new independent array**.
- It **owns its own data**.
- Changes made to the copy **do not affect** the original array.
- Changes to the original array **do not affect** the copy.

### 🔹 Key Characteristics
- A **view does not own the data**.
- Any changes made to the view **will affect** the original array.
- Any changes made to the original array **will affect** the view.
- Views are **memory efficient** because they avoid data duplication.

---


The copy SHOULD NOT be affected by the changes made to the original array.

In [ ]:
# Make a copy, change the original array, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


The view SHOULD be affected by the changes made to the original array.

In [ ]:
# Make a view, change the original array, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


The original array SHOULD be affected by the changes made to the view.

In [ ]:
# Make a view, change the view, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31
print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


## 🔍 Check if an Array Owns Its Data in NumPy

As mentioned above:

- **Copies** own the data.
- **Views** do **not** own the data — they refer to the original array's data.

---

### 🧠 How to Check?

Every NumPy array has a `.base` attribute:

- Returns `None` → the array **owns** the data.
- Returns a reference → the array is a **view**, and the `.base` points to the original array.

---

In [ ]:
# Print the value of the base attribute to check if an array owns it's data or not:

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


- The copy returns None.
- The view returns the original array.
---

## 6> 📐 What Does the Shape Tuple Represent?

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

The **shape** tuple in NumPy represents the **dimensions** of an array.

Each integer at a given index in the shape tuple indicates the **number of elements** in that corresponding dimension.

In [ ]:
# Print the shape of a 2-D array:

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

In [69]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and verify that last dimension has value 4:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


For example, if the shape tuple has a value `4` at index `4`, it means the **5th dimension (index + 1)** has **4 elements**.

---

### 🧠 Summary:
- `shape[0]` → size of 1st dimension  
- `shape[1]` → size of 2nd dimension  
- `...`
- `shape[n]` → size of (n+1)th dimension

---

## 7> 🔄 Reshaping Arrays

**Reshaping** means changing the shape of an array.

The **shape** of an array refers to the number of elements in each dimension.

By reshaping, we can:
- Add or remove dimensions
- Change the number of elements in each dimension (as long as the total number of elements remains the same)


In [71]:
# Convert the following 1-D array with 12 elements into a 2-D array.
# The outermost dimension will have 4 arrays, each with 3 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [72]:
# Convert the following 1-D array with 12 elements into a 3-D array.
# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [73]:
# Try converting 1D array with 8 elements to a 2D array with 3 elements in each dimension (will raise an error):

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [77]:
# Check if the returned array is a copy or a view:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)       # This example returns the original array, so it is a view.

[1 2 3 4 5 6 7 8]


### ❓ Unknown Dimension in NumPy

You are allowed to have **one "unknown" dimension** when reshaping arrays in NumPy.

This means you don't need to specify the exact size for one of the dimensions in the `reshape()` method.

Use `-1` as the value for that dimension, and **NumPy will automatically calculate** the correct number based on the array's total size.

📝 Note: You can only have **one unknown dimension** per reshape operation.


In [78]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [80]:
# Convert the array into a 1D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc.

These fall under Intermediate to Advanced section of numpy.

---