In [27]:
# Find the output of the below python program:

list1 = [10,20,30]
list2 = [30,10,20]
 
print("list1 + list 2 = : ", list1 + list2)   #statement 1
 
print( "list1 * 2 = : ", list1 * 2 ) #statement 2

list1 + list 2 = :  [10, 20, 30, 30, 10, 20]
list1 * 2 = :  [10, 20, 30, 10, 20, 30]


Explanation

When addition(+) operator uses list as its operands then the two lists will get concatenated. And when a list id multiplied with a constant k>=0 then the same list is appended k times in the original list.

array are compatible faster than list

In [1]:
import numpy as np

In [2]:
B = np.array([(7.8, 9, 10)
              ,(45, 5, 6)
              ,(33,44,55)])
B[0][0]=99
B

array([[99.,  9., 10.],
       [45.,  5.,  6.],
       [33., 44., 55.]])

In [3]:
A = np.array([[3,4,5],
             [6.9,7+8j,8]])
A[0][0]=99
A

array([[99. +0.j,  4. +0.j,  5. +0.j],
       [ 6.9+0.j,  7. +8.j,  8. +0.j]])

# 2.1 Numpy array creation and its attributes

In [4]:
dir(np) # check all the methods in the numpy module

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [5]:
# Creation of an Numpy Array (Vector)
A = np.array([1,2,5,9])

# numpy.ndarray
print(type(A))
print("size is ",A.size)
print("shape of A is",A.shape)
print("dimension of A",A.ndim)
print("item size of A",A.itemsize)

# default dtype('int64')
print("data type",A.dtype) 
# Note that if we put dot after each element , it changes to float.
print(A[0])
print(A.dtype)

# Change Data Type
A = np.array([1,2,3],dtype='float32') # User defined datatype
print(A)

# Altenatively astype() method
A.astype((np.float64))

<class 'numpy.ndarray'>
size is  4
shape of A is (4,)
dimension of A 1
item size of A 8
data type int64
1
int64
[1. 2. 3.]


array([1., 2., 3.])

In [6]:
# Creation of multidimensional Array

A = np.array([[1,2],
              [2,4]])
print("2D array A:\n",A)

# or

B = np.array([(7.8, 9, 10), (45, 5, 6)])
print("2D array B:\n",B)

# Alternatively
A = np.array(([1,2],[2,3]),ndmin=2)
print("2D array A:\n",A)

# Creation of 3 dimensional Matrix
A = np.array([[[1,2,3],[2,3,4],[4,5,6]],
[[7,8,9],[12,13,14],[14,15,16]],
[[27,28,29],[22,23,24],[24,25,26]]])
print("3D array A:")
print(A)

2D array A:
 [[1 2]
 [2 4]]
2D array B:
 [[ 7.8  9.  10. ]
 [45.   5.   6. ]]
2D array A:
 [[1 2]
 [2 3]]
3D array A:
[[[ 1  2  3]
  [ 2  3  4]
  [ 4  5  6]]

 [[ 7  8  9]
  [12 13 14]
  [14 15 16]]

 [[27 28 29]
  [22 23 24]
  [24 25 26]]]


In [7]:
# Data Types for Strings
A =np.array(["hello", "world citizen"])
print(A.dtype) # dtype('<U13') 13 characters

# Unique items in an array 7 Counts
A = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(A)
print(unique_values)

unique_values, indices_list = np.unique(A, return_index=True)
print(indices_list) # an array of first index positions of unique values

unique_values, occurrence_count = np.unique(A, return_counts=True)
print(occurrence_count) #frequency count of unique values in a NumPy array

<U13
[11 12 13 14 15 16 17 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]
[3 2 2 2 1 1 1 1 1 1]


In [8]:
ar = ["3", "4"]
a = np.array(ar, dtype=np.int32)  # Convert to int32 during array creation
print(a, type(a))


[3 4] <class 'numpy.ndarray'>


# 2.1.1 Creation of Numpy Array using functions

In [9]:
A = np.arange(3) # array([0, 1, 2])
print(A)

A = np.arange(1,5) # start to Stop-1 \& array([1, 2, 3, 4])
print(A)

A = np.arange(1,10,2) # start to Stop-1 with step \& array([1, 3, 5, 7, 9])
print(A)

A = np.linspace(4, 20, 6) #array([ 4. , 7.2, 10.4, 13.6, 16.8, 20. ])
print(A)

A = np.array(range(4)) # array([0, 1, 2, 3])
print(A)

z = np.array([i % 4 for i in range(14)]) # Using List Comprehension
print(z)



[0 1 2]
[1 2 3 4]
[1 3 5 7 9]
[ 4.   7.2 10.4 13.6 16.8 20. ]
[0 1 2 3]
[0 1 2 3 0 1 2 3 0 1 2 3 0 1]


In [10]:
A = np.zeros(4) # array([0., 0., 0., 0.])
print(A)
print()

A = np.zeros((3,4)) #array([[0., 0., 0., 0.],[0., 0., 0., 0.],[0.,0., 0., 0.]])
print(A)
print()

A = np.zeros((3,4,3)) #array([[0., 0., 0., 0.],[0., 0., 0., 0.],[0., 0., 0., 0.]])
print(A)
print()

A = np.ones((2, 3, 4), dtype=np.int16)
print(A)
print()

A = np.empty((2, 3)) # Random elements
print(A)
print()

A = np.eye(3) #array([[1., 0., 0.], [0., 1., 0.],[0., 0., 1.]])
print(A)
print()

A = np.diag([1, 2, 3]) # array([[1, 0, 0],[0, 2, 0],[0, 0, 3]])
print(A)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]

[[ 4.   7.2 10.4]
 [13.6 16.8 20. ]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [11]:
#Vandermonde matrix useful for Least square
A = np.vander(np.linspace(0, 2, 5), 2)
print(A)

B = np.vander([1, 2, 3, 4], 2)
print(B)

C= np.vander((1, 2, 3, 4), 4)
print(C)

[[0.  1. ]
 [0.5 1. ]
 [1.  1. ]
 [1.5 1. ]
 [2.  1. ]]
[[1 1]
 [2 1]
 [3 1]
 [4 1]]
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [12]:
# Random Matrix
rand_gen = np.random.default_rng(42) #instance of default random number generator
A=rand_gen.random((2,3)) # array([[0.77395605, 0.43887844, 0.85859792],[0.69736803, 0.09417735,0.97562235]])
A

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

# 2.2 Adding, removing, and sorting elements

In [13]:
A = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print("sorted array:",np.sort(A)) # other functions are argsort,lexsort,searchsorted \& Partition

A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

print(np.concatenate((A, B),axis=0))

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

#Concatenate along axis = 0
np.concatenate((x, y), axis=0)

sorted array: [1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]


array([[1, 2],
       [3, 4],
       [5, 6]])

# 2.3 Indexing and slicing

In [24]:
A = np.arange(5)**2 # array([ 0, 1, 4, 9, 16])
print("A:",A)

B = A[1:4] # array([1, 4, 9])
print("B:",B)

print(A[:5]) # array([ 0, 1, 4, 9, 16])

print(A[:len(A)+1]) #array([ 0, 1, 4, 9, 16])

print(A[0:]) # array([ 0, 1, 4, 9, 16])
print(A[:-1]) #array([0, 1, 4, 9])

print(A[::-1])

print(A[0:5:2])

# Slicing 2D Numpy Array
A = np.array([[4,5,6],
              [7,8,9],
              [10,11,12]])

print(A[:,1]) # array([ 5, 8, 11]) All rows 2nd column
print(A[1,:]) # array([7, 8, 9]) All columns 2nd row
print(A[0:3,0:2]) #array([[ 4, 5], [ 7, 8],[10, 11]])
A[-1] # the last row. Equivalent to A[-1, :]

A: [ 0  1  4  9 16]
B: [1 4 9]
[ 0  1  4  9 16]
[ 0  1  4  9 16]
[ 0  1  4  9 16]
[0 1 4 9]
[16  9  4  1  0]
[ 0  4 16]
[ 5  8 11]
[7 8 9]
[[ 4  5]
 [ 7  8]
 [10 11]]


array([10, 11, 12])

In [22]:
print(ord('A'))
chr(65)

65


'A'

# 2.4 Vector and Matrix calculus with Numpy Arrays

In [15]:
# Vector Calculus

A = np.arange(0, 7)
B = np.arange(7, 0, -1)
print("A:\n",A,"\nB:\n",B)
print("A+B:\n",A + B)
print("A*B\n",A * B) # Element wise Multiplication
print("A**B\n",A ** B) # Element wise exponentiation
print("A.B:\n",np.dot(A,B)) # Dot product of two vectors
print("A.B:\n",A.dot(B)) # Another Dot product of two vectors

# Matrix Calculus

A = np.array([[1, 1],[0, 1]])
B = np.array([[2, 0],[3, 4]])
print("element wise:\n",A * B) # element-wise product
print("matrix:\n",A @ B) # matrix product
print(A.dot(B)) # another matrix product

# Iterator over all element in an array
for element in A.flat:
    print(element)

# Inverse of Matrix
inv_A = np.linalg.inv(A) # Use linalg method
print(inv_A)

A:
 [0 1 2 3 4 5 6] 
B:
 [7 6 5 4 3 2 1]
A+B:
 [7 7 7 7 7 7 7]
A*B
 [ 0  6 10 12 12 10  6]
A**B
 [ 0  1 32 81 64 25  6]
A.B:
 56
A.B:
 56
element wise:
 [[2 0]
 [0 4]]
matrix:
 [[5 4]
 [3 4]]
[[5 4]
 [3 4]]
1
1
0
1
[[ 1. -1.]
 [ 0.  1.]]


# 2.5 Array’s Shape Manipulation and Stacking

In [16]:
# Create a random Matrix
rg=np.random.default_rng(42)
A = np.floor(10 * rg.random((3, 4)))
print("Array A:\n",A)

x = A.ravel() # returns the array, flattened but a reference to the parent array (i.e., a "view")
x[0] = 9
print("x:\n",x)
print("now\n",x,"\n",A)

# Or alternatively
y = A.flatten() # flatten, changes to your new array wont change the parent array.
print("y:\n",y)
y[0]=8
print("now\n",y,"\n",A)

z = A.reshape(6, 2) # returns the array with a modified shape
print("z:\n",z)

print("transpose:\n",A.T) # returns the array, transposed

Array A:
 [[7. 4. 8. 6.]
 [0. 9. 7. 7.]
 [1. 4. 3. 9.]]
x:
 [9. 4. 8. 6. 0. 9. 7. 7. 1. 4. 3. 9.]
now
 [9. 4. 8. 6. 0. 9. 7. 7. 1. 4. 3. 9.] 
 [[9. 4. 8. 6.]
 [0. 9. 7. 7.]
 [1. 4. 3. 9.]]
y:
 [9. 4. 8. 6. 0. 9. 7. 7. 1. 4. 3. 9.]
now
 [8. 4. 8. 6. 0. 9. 7. 7. 1. 4. 3. 9.] 
 [[9. 4. 8. 6.]
 [0. 9. 7. 7.]
 [1. 4. 3. 9.]]
z:
 [[9. 4.]
 [8. 6.]
 [0. 9.]
 [7. 7.]
 [1. 4.]
 [3. 9.]]
transpose:
 [[9. 0. 1.]
 [4. 9. 4.]
 [8. 7. 3.]
 [6. 7. 9.]]


In [17]:
A = np.arange(30)
B = A.reshape((2, 5, -1)) # -1 means "whatever is needed"  into_parts , rows , columns
# print(B)
print(B) # Its shape is (2, 5, 3) i.e two 5 by 3 matrix
print(B.shape)
# The reshape function returns its argument with a modified shape,
# whereas the ndarray.resize method modifies the array itself.
A.resize(3,2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
(2, 5, 3)


ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [ ]:
A = np.arange(30)
B = A.reshape((-1, 5, 6)) # -1 means "whatever is needed"  into_parts , rows , columns
# print(B)
print(B) # Its shape is (2, 5, 3) i.e two 5 by 3 matrix
print(B.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]]
(1, 5, 6)


In [ ]:
# Stacking together different arrays
A = np.array([[2,3],[4,5]])
B = np.array([[7,8],[9,10]])

print("Vertical stacks:\n",np.vstack((A, B))) # Vertical Stacking stacks along their first axes
print("Horizontal Stacks:\n",np.hstack((A, B))) # Horizontal Stacking stacks along their second axes

# Column stacking by converting row into column vector & then stacks along column
A = np.array([6, 7])
B = np.array([8, 9])
print("A:\n",A,"\nB:\n",B)
print("column stack:\n",np.column_stack((A, B))) # returns a 2D array
# Or
print()
print(np.vstack((A.T,B.T)))

Vertical stacks:
 [[ 2  3]
 [ 4  5]
 [ 7  8]
 [ 9 10]]
Horizontal Stacks:
 [[ 2  3  7  8]
 [ 4  5  9 10]]
A:
 [6 7] 
B:
 [8 9]
column stack:
 [[6 8]
 [7 9]]

[[6 7]
 [8 9]]


In [ ]:
# Use of Newaxis & increasing the dimensions from 1D to 2D
A = np.array([6, 7])
A.shape # Its shape is (2,)
B = A[:, np.newaxis] # view A as a 2D column vector
B.shape # Its shape is 2 by 1
B = A[np.newaxis,:]
B.shape # Its shape is 1 by 2
# Or Use np.expand_dims to add an axis at index position 1 with:
B = np.expand_dims(A, axis=1)
B.shape
# Fliping an Array
A = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_A = np.flip(A)
# For Matrix A
reversed_arr_rows = np.flip(A, axis=0)
# reversed_arr_columns = np.flip(A, axis=1)
reversed_arr_columns = np.flip(A, axis=0)

# 2.6 Save and load NumPy objects

In [ ]:
import numpy as np

In [ ]:
A = np.array([1, 2, 3, 4, 5, 6])
np.save('filename', A) # Saving it as "filename.npy"
B = np.load('filename.npy')

# Save a NumPy array as a plain text file like a .csv or .txt file with np.savetxt
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# savetxt() and loadtxt() functions accept additional optional

# parameters such as header, footer, and delimiter.
np.savetxt('new_file.csv', csv_arr)
np.loadtxt('new_file.csv')

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
import numpy as np

# Saving a NumPy array to a binary file (.npy)
A = np.array([1, 2, 3, 4, 5, 6])
np.save('filename.npy', A)

# Loading from the binary file
B = np.load('filename.npy')

# Saving a NumPy array to a CSV file with a header, footer, and a comma delimiter
csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.savetxt('new_file.csv', csv_arr, delimiter=',', header='Header: My Data', footer='Footer: End of Data', fmt='%d')

# Loading the CSV file
loaded_csv = np.loadtxt('new_file.csv', delimiter=',')

# 2.7 Advanced Concepts in Numpy

2.7.1 Structured arrays in Numpy
Structured arrays are ndarrays whose datatype is a composition of simpler
datatypes organized as a sequence of named fields. For example,

In [ ]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
)
# Here x is a one-dimensional array of length two whose datatype is
#a structure with three fields:
# 1. A string of length 10 or less named 'name'
# 2. a 32-bit integer named 'age'
# 3. a 32-bit float named 'weight'
x[1] # ('Fido', 3, 27.)
x['age'] # array([9, 3], dtype=int32)

# 2.7.2 Advanced indexing in Numpy

In [ ]:
A = np.arange(12)**2                    # the first 12 square numbers
i = np.array([1, 1, 3, 8, 5])           # an array of indices
print(A[i])                             # the elements of A at the positions i
# Output - array([ 1, 1, 9, 64, 25])

j = np.array([[3, 4], [9, 7]])          # A bidimensional array of indices
print(A[j])                             # the same shape as `j`
# Output - array([[ 9, 16],[81, 49]])

A = np.arange(12).reshape(3, 4)
i = np.array([[0, 1],[1, 2]])           # indices for the first dim of A
j = np.array([[2, 1],[3, 3]])           # indices for the second dim of A
print(A[i, j])                          # i and j must have equal shape
# Its is same as A[l] where l = (i,j)

print(A[i, 2])
print(A[:, j])

[ 1  1  9 64 25]
[[ 9 16]
 [81 49]]
[[ 2  5]
 [ 7 11]]
[[ 2  6]
 [ 6 10]]
[[[ 2  1]
  [ 3  3]]

 [[ 6  5]
  [ 7  7]]

 [[10  9]
  [11 11]]]


# Join and Split

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([[51,41],
                 [71,81]])
arr2 = np.array([[15,14],
                 [17,18]])
print(np.concatenate([arr1,arr2]))

[[51 41]
 [71 81]
 [15 14]
 [17 18]]


In [ ]:
print(np.concatenate([arr1,arr2],axis=0))

[[51 41]
 [71 81]
 [15 14]
 [17 18]]


In [ ]:
print(np.concatenate([arr1,arr2],axis=1))

[[51 41 15 14]
 [71 81 17 18]]


In [ ]:
print(np.hstack([arr1,arr2]))

[[51 41 15 14]
 [71 81 17 18]]


In [ ]:
print(np.vstack([arr1,arr2]))

[[51 41]
 [71 81]
 [15 14]
 [17 18]]


In [ ]:
a = np.array([11,22,33,44,55,66,77,88,99])
b = np.array_split(a,3)
# b = np.hsplit(a,3)
b[1]

array([44, 55, 66])

In [ ]:
even = a>33
new = a[even]
print(new)

[44 55 66 77 88 99]


In [ ]:
c = a*2
c

array([ 22,  44,  66,  88, 110, 132, 154, 176, 198])

In [ ]:
d = np.array([44,33,55,66,88])
fa = d%2==0
new = d[fa]
new

array([44, 66, 88])

# Statistical Function

In [ ]:
import numpy as np
import statistics as stats

In [ ]:
baked_food = [200,150,150,130,200,180,170,188]
a=np.array(baked_food)
print(np.mean(a))
print(np.average(a))
print(np.median(a))
print(stats.mode(a))
print(np.std(a))
print(np.var(a))

171.0
171.0
175.0
200
24.020824298928627
577.0


In [ ]:
tobbaco_consumption = [30,50,10,30,40,50]
deaths = [100,120,146,150,70,112]
print(np.corrcoef([tobbaco_consumption,deaths]))

[[ 1.         -0.47249791]
 [-0.47249791  1.        ]]
