## 1> 🔁 Iterating Arrays

**Iterating** means going through elements one by one.

In NumPy, since we often work with **multi-dimensional arrays**, we can iterate over them using **basic Python `for` loops**.

Each iteration gives access to elements or sub-arrays depending on the array's dimensionality.

In [1]:
# Iterate on the elements of the following 1-D array:

import numpy as np
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

1
2
3


In [2]:
# Iterate on the elements of the following 2-D array:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [8]:
# Iterate on each scalar element of the 2-D array:

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y,end=' ')

1 2 3 4 5 6 

In [9]:
# Iterate on the elements of the following 3-D array:

import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [13]:
# Iterate down to the scalars:

import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(z,end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

### 🔁 Iterating Arrays Using `nditer()`

The function **`nditer()`** is a utility in NumPy that supports iteration over arrays, from **very basic to highly advanced** use cases.

It helps solve common challenges when iterating through multi-dimensional arrays.

---

### 🎯 Iterating on Each Scalar Element

In basic `for` loops, iterating through each scalar element of a multi-dimensional array requires **nested loops**. This becomes difficult and less readable for arrays with high dimensionality.

The `nditer()` function simplifies this by allowing iteration over **each scalar element** using a **single loop**, regardless of the array's number of dimensions.


In [14]:
# Iterate through the following 3-D array:

import numpy as np
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


### 🔁 Iterating Array With Different Data Types

When using `nditer()`, we can change the **data type of elements while iterating** by using the `op_dtypes` argument and passing the desired data type.

---

### 🧠 Important Notes:
- NumPy **does not change** the data type **in-place** (i.e., directly in the original array).
- Instead, it uses an **intermediate buffer** to hold the converted values.
- To enable this behavior, we must pass `flags=['buffered']` to `nditer()`.

This allows for safe and flexible iteration with **on-the-fly data type conversion**.


In [15]:
# Iterate through the array as a string:

import numpy as np
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


Iterating With Different Step Size
    --- We can use filtering and followed by iteration.

In [17]:
# Iterate through every scalar element of the 2D array skipping 1 element:

import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [38]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        print(arr[i][j])

1
2
3
4
5
6
7
8


### 🔢 `enumerate()` in Python

The `enumerate()` function in Python adds a **counter** to an iterable and returns it as an `enumerate` object.

It is commonly used in loops when both the **index** and the **value** of elements are needed.

---

### 🧠 Key Features:
- Works with any iterable (lists, tuples, strings, etc.)
- Returns pairs of **(index, value)**
- Improves readability and avoids manual index tracking

---

### 📌 Syntax:
```python
enumerate(iterable, start=0)


In [19]:
fruits = ['apple', 'banana', 'cherry']

for index, fruit in enumerate(fruits):
    print(index, fruit)

0 apple
1 banana
2 cherry


In [21]:
for i, fruit in enumerate(fruits):
    print(i, fruit)

0 apple
1 banana
2 cherry


In [26]:
# Enumerate on following 2D array's elements:

import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

for idx, x in enumerate(arr):
  print(idx, x)

0 [1 2 3 4]
1 [5 6 7 8]


In [31]:
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

for row_idx, row in enumerate(arr):
    for col_idx, value in enumerate(row):
        print(f"arr[{row_idx}][{col_idx}] = {value}")


arr[0][0] = 1
arr[0][1] = 2
arr[0][2] = 3
arr[0][3] = 4
arr[1][0] = 5
arr[1][1] = 6
arr[1][2] = 7
arr[1][3] = 8


### 🔢 Enumerated Iteration Using `ndenumerate()`

**Enumeration** means assigning a sequence number (or index) to items one by one.

When iterating through a NumPy array, there are cases where we also need the **index** of each element.

NumPy provides the **`ndenumerate()`** method to handle such use cases. It allows iteration over each element **along with its index** in a multi-dimensional array.


In [22]:
# Enumerate on following 1D arrays elements:

import numpy as np
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [25]:
# Enumerate on following 2D array's elements:

import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


---

## 2> 🔗 Joining NumPy Arrays

**Joining** means combining the contents of two or more arrays into a single array.

Unlike SQL (where we join tables based on a key), in **NumPy**, we join arrays **based on axes**.

---

### 📌 How it works:

- Use the `concatenate()` function to join arrays.
- Pass a **sequence of arrays** to be joined.
- You can specify the **axis** along which the arrays should be joined.
  - If `axis` is **not specified**, it defaults to `0`.

This is useful for combining arrays in both **row-wise** and **column-wise** operations.


In [42]:
# Join two arrays

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [45]:
# Join two 2-D arrays along rows (axis=1):

import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


### 📚 Joining Arrays Using Stack Functions

**Stacking** is similar to **concatenation**, with the key difference being that **stacking is done along a new axis**.

---

### 🧱 Key Points:

- You can **stack** 1-D arrays along a new axis to create a higher-dimensional array.
- For example, stacking two 1-D arrays along axis 1 places them **on top of each other**.
- Use the `stack()` function and pass a sequence of arrays along with the `axis` parameter.
- If `axis` is not specified, it defaults to `0`.

Stacking is useful when you want to **preserve the shape** of the original arrays but combine them into a new dimension.


In [47]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


NumPy provides a helper function: hstack() to stack along rows.

In [54]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


NumPy provides a helper function: vstack()  to stack along columns.

In [50]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [53]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


---

## 3> ✂️ Splitting NumPy Arrays

**Splitting** is the reverse operation of **joining**.

- **Joining** merges multiple arrays into one.
- **Splitting** breaks a single array into multiple arrays.

---

### 🧠 How to Split:

Use the `array_split()` function:

- Pass the array to be split.
- Specify the number of desired splits.

NumPy will divide the array into approximately equal-sized sub-arrays.


In [62]:
# Split the array in 3 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [64]:
# Split the array in 4 parts:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


Note: We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

### 🧩 Split Into Arrays

The return value of the `array_split()` method is a **list of NumPy arrays**, where each element in the list is one of the splits.

---

### 📌 Example Use Case:

If you split an array into 3 parts using `array_split()`, the result is a list containing 3 arrays.

You can access each split using standard indexing:

- `splits[0]` → first split
- `splits[1]` → second split
- `splits[2]` → third split

This allows easy access and manipulation of each sub-array after splitting.


In [67]:
# Access the splitted arrays:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [68]:
# Split the 2-D array into three 2-D arrays.

import numpy as np
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [70]:
# Split the 2-D array into three 2-D arrays.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [71]:
# Split the 2-D array into three 2-D arrays along columns.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


An alternate solution is using hsplit() opposite of hstack()

In [73]:
# Use the hsplit() method to split the 2-D array into three 2-D arrays along columns.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


**Note**: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

---

### 4> 🔍 Searching Arrays

You can **search** a NumPy array for a specific value and retrieve the **indexes** where matches occur.

---

### 📌 How to Search:

Use the `where()` method to perform the search.

- It returns a tuple of indexes where the condition is `True`.
- Commonly used to find the **position of elements** matching a value or condition.

This is useful for filtering or locating elements in large datasets.


In [92]:
# Find the indexes where the value is 4:

import numpy as np
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)  

print(x, x[0], x[0][0],sep="       ")

(array([3, 5, 6]),)       [3 5 6]       3


In [93]:
# Find the indexes where the values are even:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [95]:
# Find the indexes where the values are odd:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


### 🔎 Search Sorted

NumPy provides a method called `searchsorted()` that performs a **binary search** on a **sorted array**.

---

### 📌 Purpose:

The `searchsorted()` method returns the **index** where a specified value should be **inserted** to maintain the array's sorted order.

- Assumes the array is already **sorted**.
- Useful for **fast lookups** or **insertion index determination**.

This method is efficient and commonly used in **searching and insertion scenarios** involving ordered data.


In [98]:
# Find the indexes where the value 7 should be inserted:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


Search From the Right Side

By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [100]:
# Find the indexes where the value 7 should be inserted, starting from the right:

import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


Multiple Values

To search for more than one value, use an array with the specified values.

In [104]:
# Find the indexes where the values 2, 4, and 6 should be inserted:

import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


The return value is an array: [1 2 3] containing the three indexes where 2, 4, 6 would be inserted in the original array to maintain the order.

---

## 5> 🔢 Sorting Arrays

**Sorting** means arranging elements in an **ordered sequence**.

An ordered sequence is any sequence that follows a specific order — such as **numeric** or **alphabetical**, in **ascending** or **descending** order.

---

### 📌 Sorting in NumPy:

NumPy provides the `sort()` function available on the `ndarray` object.

- It returns a **sorted copy** of the array.
- The original array remains unchanged.
- Can be applied to **1D, 2D, or nD arrays**.

This is useful for organizing data, comparisons, or preparing datasets for analysis.


In [106]:
# Sort the array:

import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))         # Note: This method returns a copy of the array, leaving the original array unchanged.

[0 1 2 3]


In [107]:
# Sort the array alphabetically:

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [108]:
# Sort a boolean array:

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [109]:
# If you use the sort() method on a 2-D array, both arrays will be sorted:

import numpy as np
arr = np.array([[3, 2, 4],
                [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


---

## 6> 🚿 Filtering Arrays

**Filtering** means extracting specific elements from an existing array to create a **new array**.

---

### 🧠 How Filtering Works in NumPy:

In NumPy, you filter arrays using a **boolean index list**.

- A **boolean index list** is an array of boolean values (`True` or `False`) corresponding to the **indexes** of the original array.
- If the value at a given index is `True`, the element at that index is **included** in the filtered result.
- If the value is `False`, the element is **excluded**.

This method is powerful for **conditional selection** and **data subsetting**.


In [112]:
# Create an array from the elements on index 0 and 2:

import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)
# The example above will return [41, 43], why?
# Because the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.

[41 43]


Creating the Filter Array

In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

In [114]:
# Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, False, True, True]
[43 44]


In [115]:
# Create a filter array that will return only even elements from the original array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


Creating Filter Directly From Array
- The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.
- We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [117]:
# Create a filter array that will return only values higher than 42:

import numpy as np

arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [118]:
# Create a filter array that will return only even elements from the original array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False  True False  True False  True False]
[2 4 6]
