# Getting started with Numpy

In [1]:
import numpy as np

l=[2,3,4,5]
print(l)
print(type(l))
print()
arr=np.array(l)
print(arr)
print(type(arr))

[2, 3, 4, 5]
<class 'list'>

[2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
a=np.array([1,2,3,4])
b=np.array([[1,2,3,4],[5,6,7,8]])
print(a.ndim)
print(b.ndim)

1
2


In [3]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b.shape)
print(b.size)
print(b.dtype)

(2, 4)
8
int64


In [4]:
# Python Program illustrating
# numpy.zeros method
 
import numpy as geek
 
b = geek.zeros(2, dtype = int)
print("Matrix b : \n", b)
 
a = geek.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)
 
c = geek.zeros([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# Python Program illustrating
# numpy.ones method
 
import numpy as geek
 
b = geek.ones(2, dtype = int)
print("Matrix b : \n", b)
 
a = geek.ones([2, 2], dtype = int)
print("\nMatrix a : \n", a)
 
c = geek.ones([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [1 1]

Matrix a : 
 [[1 1]
 [1 1]]

Matrix c : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Reshape and Random Number Generator



In [6]:
# Python program explaining
# numpy.random.random() function
  
# importing numpy
import numpy as geek
  
  
# output array
out_arr = geek.random.random(3)
print ("Output 1D Array filled with random floats : ", out_arr)

Output 1D Array filled with random floats :  [0.95291505 0.4236675  0.24503565]


In [7]:
# Python Programming illustrating
# numpy.arange method
 
import numpy as geek
 
print("A\n", geek.arange(4).reshape(2, 2), "\n")
print("A\n", geek.arange(4, 10), "\n")
print("A\n", geek.arange(4, 20, 3), "\n")

A
 [[0 1]
 [2 3]] 

A
 [4 5 6 7 8 9] 

A
 [ 4  7 10 13 16 19] 



In [8]:
# Python Programming illustrating
# numpy.linspace method
 
import numpy as geek
 
# restep set to True
print("B\n", geek.linspace(2.0, 3.0, num=5, retstep=True), "\n")
 
# To evaluate sin() in long range
x = geek.linspace(0, 2, 10)
print("A\n", geek.sin(x))

B
 (array([2.  , 2.25, 2.5 , 2.75, 3.  ]), np.float64(0.25)) 

A
 [0.         0.22039774 0.42995636 0.6183698  0.77637192 0.8961922
 0.9719379  0.99988386 0.9786557  0.90929743]


In [9]:
# Python Program illustrating
# numpy.reshape() method
 
import numpy as geek
 
# array = geek.arrange(8)
# The 'numpy' module has no attribute 'arrange'
array1 = geek.arange(8)
print("Original array : \n", array1)
 
# shape array with 2 rows and 4 columns
array2 = geek.arange(8).reshape(2, 4)
print("\narray reshaped with 2 rows and 4 columns : \n",
      array2)
 
# shape array with 4 rows and 2 columns
array3 = geek.arange(8).reshape(4, 2)
print("\narray reshaped with 4 rows and 2 columns : \n",
      array3)
 
# Constructs 3D array
array4 = geek.arange(8).reshape(2, 2, 2)
print("\nOriginal array reshaped to 3D : \n",
      array4)

Original array : 
 [0 1 2 3 4 5 6 7]

array reshaped with 2 rows and 4 columns : 
 [[0 1 2 3]
 [4 5 6 7]]

array reshaped with 4 rows and 2 columns : 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]

Original array reshaped to 3D : 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


# Arithmetic Operations on Array

addition

In [10]:
import numpy as np
 
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
 
# Performing addition using arithmetic operator
add_ans = a+b
print(add_ans)
 
# Performing addition using numpy function
add_ans = np.add(a, b)
print(add_ans)
 
# The same functions and operations can be used for multiple matrices
c = np.array([1, 2, 3, 4])
add_ans = a+b+c
print(add_ans)
 
add_ans = np.add(a, b, c)
print(add_ans)

[  7  77  23 130]
[  7  77  23 130]
[  8  79  26 134]
[  7  77  23 130]


subtraction

In [11]:
import numpy as np
 
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
 
# Performing subtraction using arithmetic operator
sub_ans = a-b
print(sub_ans)
 
# Performing subtraction using numpy function
sub_ans = np.subtract(a, b)
print(sub_ans)

[ 3 67  3 70]
[ 3 67  3 70]


Multiplication

In [12]:
import numpy as np
 
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
 
# Performing multiplication using arithmetic operator
mul_ans = a*b
print(mul_ans)
 
# Performing multiplication using numpy function
mul_ans = np.multiply(a, b)
print(mul_ans)

[  10  360  130 3000]
[  10  360  130 3000]


# Division

In [13]:
import numpy as np
 
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
 
# Performing division using arithmetic operators
div_ans = a/b
print(div_ans)
 
# Performing division using numpy functions
div_ans = np.divide(a, b)
print(div_ans)

[ 2.5        14.4         1.3         3.33333333]
[ 2.5        14.4         1.3         3.33333333]


In [14]:
# import numpy library
import numpy
 
# creating a numpy array of integers
arr = numpy.array([1, 5, 4, 8, 3, 7])
 
# finding the maximum and
# minimum element in the array
max_element = numpy.max(arr)
min_element = numpy.min(arr)
 
# printing the result
print('maximum element in the array is: ',
      max_element)
print('minimum element in the array is: ',
      min_element)

maximum element in the array is:  8
minimum element in the array is:  1


In [15]:
# import numpy library
import numpy
 
# creating a two dimensional
# numpy array of integers
arr = numpy.array([[11, 2, 3],
                     [4, 5, 16],
                      [7, 81, 22]])
 
# finding the maximum and
# minimum element in the array
max_element = numpy.max(arr)
min_element = numpy.min(arr)
 
# printing the result
print('maximum element in the array is:',
      max_element)
print('minimum element in the array is:',
      min_element)

maximum element in the array is: 81
minimum element in the array is: 2


In [16]:
# import numpy library
import numpy
 
# creating a two dimensional
# numpy array of integers
arr = numpy.array([[11, 2, 3],
                     [4, 5, 16],
                      [7, 81, 22]])
 
# finding the maximum and
# minimum element in the array
max_element_column = numpy.max(arr, 0)
max_element_row = numpy.max(arr, 1)
 
min_element_column = numpy.amin(arr, 0)
min_element_row = numpy.amin(arr, 1)
 
# printing the result
print('maximum elements in the columns of the array is:',
      max_element_column)
 
print('maximum elements in the rows of the array is:',
      max_element_row)
 
print('minimum elements in the columns of the array is:',
      min_element_column)
 
print('minimum elements in the rows of the array is:',
      min_element_row)

maximum elements in the columns of the array is: [11 81 22]
maximum elements in the rows of the array is: [11 16 81]
minimum elements in the columns of the array is: [4 2 3]
minimum elements in the rows of the array is: [2 4 7]


# Array Sorting

In [17]:
import numpy as np
 
# sort along the first axis
a = np.array([[12, 15],
              [10, 1]])
arr1 = np.sort(a, axis = 0)       
print ("Along first axis : \n", arr1)       
 
 
# sort along the last axis
a = np.array([[10, 15],
              [12, 1]])
arr2 = np.sort(a, axis = -1)       
print ("\nAlong first axis : \n", arr2)
 
 
a = np.array([[12, 15],
              [10, 1]])
arr1 = np.sort(a, axis = None)       
print ("\nAlong none axis : \n", arr1)

Along first axis : 
 [[10  1]
 [12 15]]

Along first axis : 
 [[10 15]
 [ 1 12]]

Along none axis : 
 [ 1 10 12 15]


In [18]:
arr = np.array([[7,3,8,6,4], [7,2,9,8,6],[5,4,2,3,1]])
print(np.sort(arr , axis = 0, kind = 'mergesort'))
print()
print(np.sort(arr , axis = 1, kind = 'quicksort'))
print()
print(np.sort(arr , kind = 'heapsort'))

[[5 2 2 3 1]
 [7 3 8 6 4]
 [7 4 9 8 6]]

[[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]

[[3 4 6 7 8]
 [2 6 7 8 9]
 [1 2 3 4 5]]


# Array Merging

In [19]:
# Python program explaining
# vstack() function
  
import numpy as geek
  
# input array
in_arr1 = geek.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1) 
  
in_arr2 = geek.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2) 
  
# Stacking the two arrays vertically
out_arr = geek.vstack((in_arr1, in_arr2))
print ("Output vertically stacked array:\n ", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output vertically stacked array:
  [[1 2 3]
 [4 5 6]]


In [20]:
# Python program explaining
# vstack() function
  
import numpy as geek
  
# input array
in_arr1 = geek.array([[ 1, 2, 3], [ -1, -2, -3]] )
print ("1st Input array : \n", in_arr1) 
  
in_arr2 = geek.array([[ 4, 5, 6], [ -4, -5, -6]] )
print ("2nd Input array : \n", in_arr2) 
  
# Stacking the two arrays vertically
out_arr = geek.vstack((in_arr1, in_arr2))
print ("Output stacked array :\n ", out_arr)

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3]
 [-1 -2 -3]
 [ 4  5  6]
 [-4 -5 -6]]


In [21]:
# Python program explaining
# hstack() function
  
import numpy as geek
  
# input array
in_arr1 = geek.array([ 1, 2, 3] )
print ("1st Input array : \n", in_arr1) 
  
in_arr2 = geek.array([ 4, 5, 6] )
print ("2nd Input array : \n", in_arr2) 
  
# Stacking the two arrays horizontally
out_arr = geek.hstack((in_arr1, in_arr2))
print ("Output horizontally stacked array:\n ", out_arr)

1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


In [22]:
# Python program explaining
# hstack() function
  
import numpy as geek
  
# input array
in_arr1 = geek.array([[ 1, 2, 3], [ -1, -2, -3]] )
print ("1st Input array : \n", in_arr1) 
  
in_arr2 = geek.array([[ 4, 5, 6], [ -4, -5, -6]] )
print ("2nd Input array : \n", in_arr2) 
  
# Stacking the two arrays horizontally
out_arr = geek.hstack((in_arr1, in_arr2))
print ("Output stacked array :\n ", out_arr)

1st Input array : 
 [[ 1  2  3]
 [-1 -2 -3]]
2nd Input array : 
 [[ 4  5  6]
 [-4 -5 -6]]
Output stacked array :
  [[ 1  2  3  4  5  6]
 [-1 -2 -3 -4 -5 -6]]


In [23]:
# Python program explaining
# numpy.concatenate() function
  
# importing numpy as geek 
import numpy as geek
  
arr1 = geek.array([[2, 4],
                   [6, 8]])

arr2 = geek.array([[3, 5],
                   [7, 9]])
  
gfg = geek.concatenate((arr1, arr2), axis = 0)
# gfg = geek.concatenate((arr1, arr2), axis = 1)
  
print (gfg)

[[2 4]
 [6 8]
 [3 5]
 [7 9]]


In [24]:
# Python program explaining
# numpy.vsplit() function
  
# importing numpy as geek 
import numpy as geek
  
arr = geek.arange(9.0).reshape(3, 3)
  
gfg = geek.vsplit(arr, 1)
  
print (gfg)

[array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])]


In [25]:
# Python program explaining
# numpy.hsplit() function
  
# importing numpy as geek 
import numpy as geek
  
arr = geek.arange(16.0).reshape(4, 4)
  
gfg = geek.hsplit(arr, 2)
  
print (gfg)

[array([[ 0.,  1.],
       [ 4.,  5.],
       [ 8.,  9.],
       [12., 13.]]), array([[ 2.,  3.],
       [ 6.,  7.],
       [10., 11.],
       [14., 15.]])]


# Arrays Slicing - DAP

In [26]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
arr[3: ]

array([4, 5, 6, 7, 8])

In [27]:
print(arr[ : -3])
print(arr[3  :  -3])

[1 2 3 4 5]
[4 5]


In [28]:
arr = np.array([[1,2,3,4],[5,6,7,8],[8,7,6,5],[4,3,2,1]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [8, 7, 6, 5],
       [4, 3, 2, 1]])

In [29]:
print(arr[ 3 , 1])
print()
print(arr[ 1: , 1:])

3

[[6 7 8]
 [7 6 5]
 [3 2 1]]


# Automating using Numpy

In [30]:
lst = [1,2,3,4,5,6,7,8,9,10]
for i in lst:
  if (i > 5):
    print(i)

6
7
8
9
10


In [31]:
lst = np.array((1,2,3,4,5,6,7,8,9,10))
# lst = np.array([1,2,3,4,5,6,7,8,9,10])
print(lst[lst>5]) #in a single line we have done the same thing which we did previously and this time without using the for loop
print([lst>5]) #in a single line we have done the same thing which we did previously and this time without using the for loop

[ 6  7  8  9 10]
[array([False, False, False, False, False,  True,  True,  True,  True,
        True])]


In [32]:
list[lst]

list[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])]

In [33]:
# not matrix multiplication
c = np.array([6, 7, 5, 8])
d = np.array([4, 3, 7, 8])
pro = c.dot(d)  
print(pro)

144


In [34]:
lst.transpose()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
import numpy as np
array_1 = np.array([1, 2, 3, 4])
array_2 = np.array([5, 6, 7, 8])
array_new = np.stack((array_1, array_2), axis=1)
print(array_new)


[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [36]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [41]:
import numpy
array1 = numpy.array([[1, 2, 3, 4, 5],[20,30,40,50,60]])
array2 = numpy.array([[6, 7, 8, 9, 10],[9,8,7,6,5]])
array1 = numpy.column_stack([array1, array2])
print(array1)

[[ 1  2  3  4  5  6  7  8  9 10]
 [20 30 40 50 60  9  8  7  6  5]]
